auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1  
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h


schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      # single-node deployment: only 1 replica
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
    # replication is controlled per-schema (schema_config.configs[].replication_factor)
    # filesystem store is declared at storage_config.filesystem below
    
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

limits_config:
  enforce_metric_name: false


